spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/flink
    username: flink
    password: flink
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    database: mysql
    hibernate:
      ddl-auto: create
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 7777