spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/inventory
    username: mysqluser
    password: mysqlpw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 7777